external_load_balancer_dns: 104.11.116.105
nat_public_ips: ["104.11.116.105"]
internal_load_balancer_dns: 10.10.10.56
egress_gateway_cidr:
haproxy_external_ip: 104.11.116.105
haproxy_internal_ip: 10.10.10.56
bastion_public_ip: 104.11.116.105
haproxy_server_fqdn: haproxy.dev1.devbaremetal.infitx-labs.com
private_subdomain: ""
public_subdomain: "dev1.devbaremetal.infitx-labs.com"
int_interop_switch_subdomain: intapi
ext_interop_switch_subdomain: extapi
target_group_internal_https_port: 31443
target_group_internal_http_port: 31080
target_group_external_https_port: 32443
target_group_external_http_port: 32080
target_group_internal_health_port: 31081
target_group_external_health_port: 32081
private_network_cidr:
ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJJwIBAAKCAgEAnfRzVxkMv3OofcBOGCgFylsp2lbYa1PR1PQ93aJSdBh4JvZv
  E5oJg3nBeSEKhAnUu7WFmbpWPS6haoJd40w9Rx8Dlb4gW9e1KdiRmQ8ookjdZQ9h
  YCi7K4X3zT8zILyJ8hk3brgyKISsut8r2mW5cxKSbd10cUmheCNR/nB9j2EtqFWR
  Z8vLCQQ/rgJZYvxxVK8jSPztIwD5PVth4tmfxpnWgbQkAznyk5r5FdrJrwwOPhqy
  1GeO0bhQvHVbslCQBdbv7RXhZo4d+g/BjDb8xqSzCmCL5wBxvK9+ZaJNvJNrrqaj
  POjerNSWK4E9vp7AHlY/W76rL0WHx6+yV+wewDdPP6IePxqcbggWEYqdeS1jrj9Y
  hJe3ve/lbOXisVSqeNTXzEW/BH1n+ZH83i7SALQkrd8lpXIBTw7gxr3kWIdao2Ld
  tJddocCJGXTXgPQnHBE1yjNQnR/BzhHD9us9UwgEQYiZbdnxBcAxfXn7SctTAA4T
  tyVK8QjyB3pISlUaB5WBlWraiHro54JO/vmWNwK1zPChJuylAfyNGNrbVRfovNOw
  Rc5J+CV0KkamC2crDWaVzGOUYIQAX7tT/idOR4kjAHIlxEMyAS9Ungv562v9IGmi
  njzb/hTQ1qzTITQ7sv+2UFguyWggOfba1HNvdZxx7IXPi60wNClTCX9CV+MCAwEA
  AQKCAgAg4l+Q5nos8ZtGct7PUKXD9y7DcgkkbxLkTuUCW2TnHqEFG5EMd6k7YgHR
  gft6ecF8QtJJqu2BV0/rqLB7PcgUInTQnACInmPtDlVhlDJVdu4AuC8Bofk1mnJ4
  nIu8aQQfDvjnaBmpLdX4IbYzhbISLu+lR9GSNE4VgOT1H95EF2s1/HqFLXxbqDLJ
  u1t4rC27/6pM67tC6lT5XSkH3V7SLfzmi+ZjdZD3AfCRiDcs5kmgzFYmuliVeNX2
  Jkis2vDhBlp09XUzsKq1AMq+skP15xwPMQJvWTxUmASsjBm7BMYKWk7pw2F4gdmx
  vPpp0QsWRcZzB0MEWGloPT/X5iSQdDgt6EZU4Sy/trPd4LhZFq/wCn50AFfQBZ4j
  Ag3ZS2kXwMCXxPMNjWJI1yPtPDNoelsIHKYHSCEAsQ9h9u6sol6LrD1YmCZ8xJDD
  B7d51uault95MR7BwuvHE5NZWAih0FbzLwknKLD20YwDzMvc20LpPMUpfyF+s/Up
  ZEa56yKmBWqb6b3IXdSlYzsdX8B8S0ZcJyIsf7nXDOofUzpFhwPnlV5Dv/wGUdJo
  2DhJQExPQ7dm5od22h5i7wKZP2bQRe7HZx2Y8Mc87uhbWUONbu7ENQTnMImO+lov
  IPcBIL6dHZjJjO5BNTJT+4Nj0ZioI++q4ECELQE41GRo4H4bwQKCAQEAymXyz3kL
  1mx/0TlQD0tCME7FnjAmVM42dqviTTZwCVEMjFD3PkyfOSJfv9E+yHAHb+Mt5dIZ
  o/P5aLrL7ynvwzsXMZEMTh+VDHg0c/+ltpCZarJoW+wSYh/nE7vZPG/ynxWhatQC
  E7QvBA/G5oIVO5z7HKGteouhrH599tiWbWV8xiG7RZbkK1XVpDfBor75gfJEf3uo
  I9Pkvaw2/5oryVpJgRYQmjhLG+RKYQcddAlV7gqAEDBGCxMymYeuRvbhXjgmM9dO
  tHZiDHORN/kE0XIJjE7M06NR82C8TZAxGJV97niUXqKfIBsVRpOiM2jyb7vCLDrp
  n2IPXb4j0b7DCwKCAQEAx8ldBoBUErKnOd9L8LwUCGUplA1NjCpxFNc2Yp6u2Hnc
  YBYYZW7lcjTSm6sz7I/3qE72fGacRpRC7Ct6DRV0YSVdAhKzvaoH/jAfnACUf2Xs
  l/1W32yX6xWrQ3vT60Gr5K1qMTQBZF5SJaz7rt+ejN0JYI0p7vzkiS83FIIfy0AK
  eJpxN5627kn8B6jnIGTJQMUx4Tq93e/7uJbzxLWNQEUTm74i7HltvAU0bjFm6+XC
  Rxw/h+HwQ4qwchMBaQI40pmMAR7zX79XknTIprFyJwkd2S3DWXJSJVGauc7xw4s6
  ngBu8J683egAVEbomzQvoaUmrIYQpqiVar4AYQ5FiQKCAQBPnQiEydV5M9aXQxcV
  3QGdJO8hCUmapD7SMUxkGNy7HXF1JEgM7nDXNYk6V6F9kGusfE1KkHlbf5WEt62O
  Vw2j2vOFoMuZU1z6ubHQSygxBvICAUmBlvuoM2pe3c5WsqZaI1UKQ3jJrV+tFlOj
  yll1yIsSORqXEKO4yUzdM1cAkyIggZY7il4YGbxeyzvUu5BDqDt/dfGuniPk5AAC
  TO+aVXSCXV6Me0Y4I3WKcxUH1sBBUUoMlCCJLLUDpVZNPcFqoWWNkMy5ubNZuH/P
  55kYleXhlgGF4kFTHaMUU3qsc+lES5P5Ibi8FUsqJtpvpIFwqAd6BHZvJlBrDGbk
  k0f/AoIBAEsYe2kIL5HfqU/tiSPx7i3BqMFHxtBa26qTwpOLRfmExLsxUvY9mu00
  wb1Vuuy+qL6Q/8F+6Fr3O7h+FyB34gjp/G3dDcbK9Los6JTA+xBwBWCUD2Vn8iqh
  OIDjOKMDSlNog7P+8k8BzSrwPKJc18HnC7FJHmwAjv6pyrBgwQarCcSPeOMJO4WS
  NbPDXy0j9SntdXRNmjSkEiAuTW6xN2jjDh3KeGIeuoqkAjMxSph9AmusSI0Q9jjN
  FsmqLyuDdExk/uUk9yIUUBxy3UEbDedyW8/Yjcc/W3U/mUMicGmqGdxuGUVExYU7
  wXPsO16rXQQLid/rfLLIR3GZ/ZZ9wNECggEAcUe6QFzxElY340tZKoNxo0MWPlOn
  7QNMCU4hs//jdAuw2ZYnojjuCWPOFc1AgLJ+aSp9uo3P1uxH0Va2I12erbZwf8Ng
  SzAGIqV1MJiR0odzJKYV0bj6SdFcNTBfHb0tjV5ThzTvnSav2lfo+EAEL025SH3/
  s4qXUbISbEunWQ0SbH4zOAzY5BdFki1L3wRr+XHMBc0Znsigczb5TPIj0ZbOh2i9
  BxqLabHDh2RG9kXxziXw7BMxjcXY2HQdGice1SOoFd79SKZbEBD0O6GqS70BABKa
  SrjJM2/42nW/0WAtTvk29bq3dJRGa3I+aN7z4zUiKB8tvFImLOO21L9Xbg==
  -----END RSA PRIVATE KEY-----
os_user_name: ubuntu
base_domain: "devbaremetal.infitx-labs.com"
kubeapi_loadbalancer_fqdn: none
master_hosts_0_private_ip: "10.10.100.58"
agent_hosts: []
master_hosts: ["10.10.100.58", "10.10.100.59", "10.10.100.60"]
k6s_callback_fqdn: none
enable_k6s_test_harness: false
test_harness_private_ip: none
route53_external_dns_access_key: "changeme"
route53_external_dns_secret_key: "changeme"
longhorn_backups_access_key: "changeme"
longhorn_backups_secret_key: "changeme"
longhorn_backups_bucket_name: dev1.devbaremetal.infitx-labs.com-lhbck
enable_ingress_k8s_lb: true
