nat_public_ips: []
internal_load_balancer_dns:
external_load_balancer_dns:
egress_gateway_cidr:
haproxy_external_ip:
haproxy_internal_ip:
bastion_public_ip:
haproxy_server_fqdn:
private_subdomain: ""
public_subdomain: "dev1.devbaremetal.infitx-labs.com"
int_interop_switch_subdomain: intapi
ext_interop_switch_subdomain: extapi
target_group_internal_https_port: 31443
target_group_internal_http_port: 31080
target_group_external_https_port: 32443
target_group_external_http_port: 32080
target_group_internal_health_port: 31081
target_group_external_health_port: 32081
private_network_cidr:
ssh_private_key:
os_user_name: ubuntu
base_domain: "devbaremetal.infitx-labs.com"
kubeapi_loadbalancer_fqdn: none
master_hosts_0_private_ip: ""
agent_hosts: []
master_hosts: [""]
k6s_callback_fqdn: none
enable_k6s_test_harness: false
test_harness_private_ip: none
route53_external_dns_access_key: "replace"
route53_external_dns_secret_key: "replace"
longhorn_backups_access_key: "replace"
longhorn_backups_secret_key: "replace"
longhorn_backups_bucket_name: dev1.devbaremetal.infitx-labs.com-lhbck
