pm4ml_chart_version: 9.0.4
pm4ml_external_mcm_public_fqdn: mcm.dev.labsk8s601.mojaloop.live
pm4ml_ingress_internal_lb: false
pm4ml_external_switch_client_id: dfsp-jwt
pm4ml_external_switch_oidc_url: https://keycloak.dev.labsk8s601.mojaloop.live
pm4ml_external_switch_oidc_token_route: realms/dfsps/protocol/openid-connect/token
pm4ml_external_switch_client_secret_vault_path: "mcmdev_client_secret"
pm4ml_external_switch_fqdn: extapi.dev.labsk8s601.mojaloop.live
pm4ml_dfsp_id: pm4mltest2
pm4ml_ttk_enabled: true
