region: eu-west-1
domain: mojalabs.io
tenant: labs11
enable_github_oauth: false
enable_netmaker_oidc: true
ansible_collection_tag: v0.2.7
gitlab_admin_rbac_group: tenant-admins
gitlab_readonly_rbac_group: tenant-viewers
smtp_server_enable: false
gitlab_version: 15.11.2
gitlab_runner_version: 15.11.0
envs:
  - env: dev
    domain: labs8.mojalabs.io
    cloud_platform: aws
    cloud_region: eu-west-1
    k8s_cluster_type: k3s
    iac_terraform_modules_tag: v0.3.28
    enable_vault_oauth_to_gitlab: true
    lets_encrypt_email: test@mojalabs.io
tags: {
  "Origin": "Terraform",
  "mojaloop/cost_center": "mlf-iac-sandbox",
  "mojaloop/env": "ft-sbox-rw",
  "mojaloop/owner": "Samuel-Kummary"
}
